[package]
name = "mod-interval"
version = "0.1.0"
authors = ["Eli Snow <EliSnow@users.noreply.github.com>"]
edition = "2018"
license = "Unlicense OR CC0-1.0"

[dependencies]
futures = "0.3"
futures-timer = "2"

[dev-dependencies]
async-std = "1"